name: flutter_point_tab_bar
description: A tab bar widget for Flutter with point indicator.
version: 0.0.2
homepage: https://github.com/hienlh/flutter_point_tab_bar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
